# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3228af6d95ffacbc105c85635f4e8c274e7402697ba40ddeeb9607041e712af26870e1d816ad0f3b4e568b79275ced36875d778a173e27748bd72af6628800b

test:
  secret_key_base: 8fc5bdc787e6f9b1bb41cd4b980b9befdf9fe41391c23f8486edb0f5200caad078ecc5c64caa1004e1df65701109625c590cf0ecc546d8093e4b5ea3eb086a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
